on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: install gems
      run: gem install cfhighlander rspec
    - name: set cfndsl spec
      run: cfndsl -u 11.0.0
    - name: cftest
      run: cfhighlander cftest
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2
